import { expect, test } from '@playwright/test'

async function signIn(page: import('@playwright/test').Page, email: string) {
  await page.goto('/login')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password').fill('password123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Ticket board.' })).toBeVisible()
}

test('employee can create and edit a ticket, but cannot access admin pages', async ({ page }) => {
  await page.goto('/tickets')
  await expect(page).toHaveURL(/\/login$/)
  await signIn(page, 'ava@paperdesk.test')
  await expect(page.getByRole('link', { name: 'Team members' })).toHaveCount(0)
  await expect(page.getByRole('row', { name: /External monitor keeps flickering/ })).toHaveCount(0)
  await page.getByRole('link', { name: 'New ticket' }).first().click()
  await page.getByLabel('Give it a short title').fill('Headset microphone is silent')
  await page.getByLabel('Tell us a little more').fill('The microphone does not register any sound in calls.')
  await page.getByText('Hardware', { exact: true }).last().click()
  await page.getByRole('button', { name: 'Send ticket' }).click()
  await expect(page.getByRole('heading', { name: 'Headset microphone is silent.' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel('Title').fill('Headset microphone works intermittently')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('heading', { name: 'Headset microphone works intermittently.' })).toBeVisible()
  await page.goto('/users')
  await expect(page).toHaveURL(/\/tickets$/)
})

test('support can filter tickets and update triage', async ({ page }) => {
  await signIn(page, 'mia@paperdesk.test')
  await expect(page.getByLabel('Assignee')).toBeVisible()
  await page.getByLabel('Assignee').selectOption('u-mia')
  await expect(page).toHaveURL(/assigneeId=u-mia/)
  await page.goto('/tickets/t-1048')
  await page.getByLabel('Status').selectOption('in_progress')
  await page.getByLabel('Priority').selectOption('high')
  await page.getByLabel('Assign to').selectOption('u-mia')
  await page.getByRole('button', { name: 'Save updates' }).click()
  await expect(page.getByText('Ticket updates saved.')).toBeVisible()
  await expect(page.locator('.detail-info').getByText('Mia Chen', { exact: true })).toBeVisible()
})

test('admin can create and deactivate a team member', async ({ page }) => {
  await signIn(page, 'sam@paperdesk.test')
  await page.getByRole('link', { name: 'Team members' }).click()
  await expect(page.getByRole('heading', { name: 'Team members.' })).toBeVisible()
  await page.getByRole('button', { name: 'Add member' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Full name').fill('Jordan Lee')
  await dialog.getByLabel('Email address').fill('jordan@paperdesk.test')
  await dialog.getByLabel('Temporary password').fill('password123')
  await dialog.getByLabel('Role').selectOption('support')
  await dialog.getByRole('button', { name: 'Add member' }).click()
  await expect(page.getByRole('row', { name: /Jordan Lee/ })).toBeVisible()
  await page.getByRole('button', { name: 'Deactivate Jordan Lee' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Deactivate' }).click()
  await expect(page.getByText("Jordan Lee's account has been deactivated.")).toBeVisible()
})

test('mobile navigation remains usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, 'ava@paperdesk.test')
  await expect(page.getByRole('heading', { name: 'Ticket board.' })).toBeVisible()
  await page.getByRole('button', { name: 'Open menu' }).click()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
  await page.getByRole('link', { name: 'My profile' }).click()
  await expect(page.getByRole('heading', { name: 'My profile.' })).toBeVisible()
})
