import { mkdir } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

test('desktop and mobile screens fit the viewport', async ({ page }) => {
  await mkdir('artifacts', { recursive: true })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: /A little less/ })).toBeVisible()
  await page.screenshot({ path: 'artifacts/login-desktop.png', fullPage: true })
  await page.getByLabel('Email address').fill('ava@paperdesk.test')
  await page.getByLabel('Password').fill('password123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Ticket board.' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'Ticket board.' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true })
  for (const route of ['/tickets/new', '/tickets/t-1048', '/profile']) {
    await page.goto(route)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  }
  const adminPage = await page.context().newPage()
  await adminPage.emulateMedia({ reducedMotion: 'reduce' })
  await adminPage.setViewportSize({ width: 390, height: 844 })
  await adminPage.goto('/signup')
  await expect.poll(() => adminPage.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await adminPage.goto('/login')
  await adminPage.getByLabel('Email address').fill('sam@paperdesk.test')
  await adminPage.getByLabel('Password').fill('password123')
  await adminPage.getByRole('button', { name: 'Sign in' }).click()
  await adminPage.goto('/users')
  await expect(adminPage.getByRole('heading', { name: 'Team members.' })).toBeVisible()
  await expect.poll(() => adminPage.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await adminPage.goto('/teams')
  await expect(adminPage.getByRole('heading', { name: 'Teams.' })).toBeVisible()
  await expect.poll(() => adminPage.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await adminPage.setViewportSize({ width: 1440, height: 900 })
  await adminPage.screenshot({ path: 'artifacts/teams-desktop.png', fullPage: true })
  await adminPage.goto('/tickets/t-1048')
  await expect(adminPage.getByRole('region', { name: "Who's involved?" })).toBeVisible()
  await adminPage.screenshot({ path: 'artifacts/coordination-desktop.png', fullPage: true })
  await adminPage.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => adminPage.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await adminPage.screenshot({ path: 'artifacts/coordination-mobile.png', fullPage: true })
  await adminPage.close()
})
